package euler_1_10;

/**
 * Created by Emmanuel on 1/23/2018.
 */
public class Problem2 {

    /**
     * ************************Even Fibonacci numbers*********************************
     * Each new term in the Fibonacci sequence is generated by adding the previous two
     * terms. By starting with 1 and 2, the first 10 terms will be:
     * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...\
     * By considering the terms in the Fibonacci sequence whose
     * values do not exceed four million, find the sum of the even-valued terms.
     * **********************************************************************************
     */

    public static int fibonacciEvenNumbers(int count) {
        int n1 = 0, n2 = 1, n3 = 0;
        int sum = 0;
        while ( n3 <= count) {
            n3 = n1 + n2;
            if (n3 % 2 == 0)
                sum += n3;
            n1 = n2;
            n2 = n3;
        }
        return sum;
    }

    public static void main(String[] args) {
        int sum = fibonacciEvenNumbers(4000000);
        System.out.println(sum);
    }
}
