package euler_1_10;

/**
 * Created by Emmanuel on 1/23/2018.
 */
public class Problem2 {

    /**
     * Each new term in the Fibonacci sequence is generated by adding the previous two
     *  terms. By starting with 1 and 2, the first 10 terms will be:
     *       1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...\
     * By considering the terms in the Fibonacci sequence whose
     * values do not exceed four million, find the sum of the even-valued terms.
     */

    public static int fibonacci (int range){
        int sum = 0;
        for (int i = 0; i < range; i++)
            if(i % 3 == 0 || i % 5 == 0)
                sum += i;
        return sum;
    }


    public static void main(String[] args) {
        int sum = fibonacci(1000);
        System.out.println(sum);
    }
}
